[package]
name = "astc-encoder-rust"
authors = ["C2Rust"]
version = "0.0.0"
publish = false
edition = "2021"

[lib]
name = "astc_encoder_rust"
path = "lib.rs"

[profile.dev]
debug = 0
[profile.test]
debug = 0
